apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.mongodb.labels.app }}
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.port }}
      protocol: TCP
